---
title: "Changes in Department Size, Fall 2016 - Spring 2019"
author: "Simone Chu"
date: "4/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(readxl)
library(fs)
library(gganimate)
library(ggthemes)
library(janitor)
library(lubridate)
library(tidyverse)
```

```{r downloading_data, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE, cache=TRUE}

# Getting the necessary data (I chose to narrow it down to the past 4 years, so I'm loading 
# eight different datasets)!

# Because some of these datasets were formatted differently (for example, in some, the column 
# that contained info about undergraduate enrollment (u_grad) was called "hcol"), I did some 
# cleaning up. I also made sure that all the column names were in snake case, for easy use later
# on. 

# Lastly, I summarized the attributes I planned to use to convey information in the graphic;
# finding the number of courses was as simple as counting the number of rows under each 
# department, and enrollment only required a sum of the undergraduates enrolled. I decided to 
# also find the mean class size to have something to base the size of each point on my plot off
# of.

download.file("https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19.xlsx", destfile = "s19.xlsx")
s19 <- read_excel("s19.xlsx", skip = 3) %>%
  clean_names() %>%
  filter(u_grad > 0) %>%
  group_by(course_department) %>%
  summarize(n_courses = n(), enrollment = sum(u_grad), avg_class_size = mean(u_grad)) %>%
  mutate(term = "2019 (Spring)")
  file_delete("s19.xlsx")
  
download.file("https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_10.24.18.xlsx", destfile = "f18.xlsx")
f18 <- read_excel("f18.xlsx", skip = 2) %>%
  clean_names() %>%
  filter(u_grad > 0) %>%
  group_by(course_department) %>%
  summarize(n_courses = n(), enrollment = sum(u_grad), avg_class_size = mean(u_grad)) %>%
  mutate(term = "2018 (Fall)")
  file_delete("f18.xlsx")

download.file("https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_03.06.18.xlsx", destfile = "s18.xlsx")
s18 <- read_excel("s18.xlsx", skip = 3) %>%
  clean_names() %>%
  filter(u_grad > 0) %>%
  group_by(course_department) %>%
  summarize(n_courses = n(), enrollment = sum(u_grad), avg_class_size = mean(u_grad)) %>%
  mutate(term = "2018 (Spring)")
  file_delete("s18.xlsx")
  
download.file("https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_10.20.17.xlsx", destfile = "f17.xlsx")
f17 <- read_excel("f17.xlsx", skip = 3) %>%
  clean_names() %>%
  filter(u_grad > 0) %>%
  group_by(course_department) %>%
  summarize(n_courses = n(), enrollment = sum(u_grad), avg_class_size = mean(u_grad)) %>%
  mutate(term = "2017 (Fall)")
  file_delete("f17.xlsx")

download.file("http://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2017_03_07_final_0.xlsx", destfile = "s17.xlsx")
s17 <- read_excel("s17.xlsx", skip = 3) %>%
  clean_names() %>%
  filter(u_grad > 0) %>%
  group_by(course_department) %>%
  summarize(n_courses = n(), enrollment = sum(u_grad), avg_class_size = mean(u_grad)) %>%
  mutate(term = "2017 (Spring)")
  file_delete("s17.xlsx")
  
download.file("http://registrar.fas.harvard.edu/files/fas-registrar/files/copy_of_class_enrollment_summary_by_term_10.06.2016.xlsx", destfile = "f16.xlsx")
f16 <- read_excel("f16.xlsx", skip = 3) %>%
  clean_names() %>%
  filter(u_grad > 0) %>%
  group_by(course_department) %>%
  summarize(n_courses = n(), enrollment = sum(u_grad), avg_class_size = mean(u_grad)) %>%
  mutate(term = "2016 (Fall)")
  file_delete("f16.xlsx")
  
# I put each semester's data in a separate set of lines of code so that R could delete the files
# as it ran -- hopefully that makes it faster? If not, I guess this was unnecessary, but I liked
# having things organized this way. 
  
```

```{r, echo=FALSE, include=TRUE, warning=FALSE, message=FALSE}

all <- bind_rows(f16, s17, f17, s18, f18, s19) %>%
  filter(!is.na(course_department)) %>%
  filter(!(course_department %in% c("No Department", "House Seminars",
                                    "Freshman Seminars",
                                    "Special Concentrations",
                                    "General Education"))) %>%
  # mutate(term = (as.Date(c("January 2019", "September 2018", "January 2018", "September 2017",
  #                          "January 2017", "September 2016"), format = '%B %Y'))) %>%
  mutate(division = case_when(
    course_department %in% c("Celtic Languages & Literatures", "Classics, The", 
                             "Comparative Literature", "East Asian Langs & Civ",
                             "English", "Germanic Languages & Lit",
                             "History of Art & Architecture", "Linguistics",
                             "Music", "Near Eastern Languages & Civ", 
                             "Philosophy", "Romance Languages & Lit",
                             "Slavic Languages & Literatures", "South Asian Studies",
                             "Theater, Dance & Media", "Folklore & Mythology",
                             "History & Literature", "Religion, The Study of",
                             "Visual & Environmental Studies", "American Studies",
                             "Humanities", "Medieval Studies", 
                             "Regional Studies-East Asia", "Ukrainian Studies",
                             "Russia, E Europe, Central Asia") ~ "Arts & Humanities",
    
    course_department %in% c("Astronomy", "Chemistry & Chemical Biology",
                             "Chemical & Physical Biology", "Earth & Planetary Sciences",
                             "Human Evolutionary Biology", "Mathematics", 
                             "Molecular & Cellular Biology", "Organismic & Evolutionary Biol",
                             "Physics", "Statistics", "Stem Cell & Regenerative Biol",
                             "Systems Biology", "Mind, Brain & Behavior",
                             "Medical Sciences", "Neurobiology",
                             "Bio Sciences in Public Health", "Biophysics",
                             "Biostatistics", "Neuroscience") ~ "Science",
    
    course_department %in% c("African & African Amer Studies", "Anthropology", 
                             "Economics", "Government", "History", 
                             "History of Science", "Psychology", 
                             "Social Studies", "Sociology",
                             "Women, Gender & Sexuality",
                             "Ethnicity, Migration, Rights",
                             "Envi Science & Public Policy", 
                             "Global Health & Health Policy", "Health Policy") 
                              ~ "Social Science",
    
    course_department %in% c("Applied Computation", "Applied Mathematics",
                             "Applied Physics", "Biomedical Engineering",
                             "Computer Science", "Engineering Sciences",
                             "Environmental Sci & Engineer") ~ "Engineering & Applied Sciences",
    
    course_department == "Expository Writing" ~ "Expository Writing"
  ))
  
# I wanted a cool way to see trends by division (i.e., Arts & Humanities, Social Sciences,
# Sciences, and SEAS), so I assigned divisions to each of the course departments. This will 
# help me make a cool graphic with nice colors later on! 

# I based the divisions on this page: https://www.fas.harvard.edu/pages/academic-divisions. 
# Sadly, not every department that appears in these datasets was accounted for by FAS, so I used # common sense to sort the rest (for example, it seemed reasonable to place "Neurobiology" under 
# the Sciences division, and "Humanities" under the Humanities division). 

# I excluded smaller "departments" like "Special Concentration" and "House Seminars" because 
# those aren't divisions the same way that the others are. 

# I kept Expository Writing just because I think it's helpful to show how the number of freshmen
# holds constant each year. 

```


```{r, echo=FALSE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}

ggplot(all, aes(x = n_courses, y = enrollment, size = avg_class_size, 
                alpha = 0.95, color = division)) +
  
# Setting the size of each point to the mean class size lets me present more information
# in an aesthetically pleasing way.
  
  geom_point() +
  theme_economist_white() +
  
# I'm a fan of the clean look of the Economist theme, but I like the look of the "white" version.
  
  theme(legend.position = "right") + 
  labs(title = "Department Size, Fall 2016 - Spring 2019",
       subtitle = "Term: {closest_state}",
       caption = "Source: FAS Registrar") + 
  
# I made sure to have the term denoted so that we could tell which term is being displayed.
  
  xlab("Number of Courses Offered") + 
  ylab("Undergraduate Enrollment") +
  scale_color_brewer(palette = "Set1") +
  guides(alpha = FALSE,
         size = guide_legend(title = "Mean Class Size", order = 2),
         color = guide_legend(title = "Academic Division", order = 1)) +

# I had to reorder the elements of the legend, because I preferred having the Academic Division
# above mean class size. 
  
  theme(legend.text=element_text(size=11)) +
  
# Originally, the font for each academic division was larger than the font that says "Academic 
# Division," so I adjusted. 
  
  transition_states(term)
  
```

